server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: cheng128
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  redis:
    host: 119.91.234.122 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: NrfV6w3FADUaYalfxQB0vC1S005ggVU80AmtA9h # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      设置逻辑删除，在执行sql时会自动拼接
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
#      用数据库的id自增，要不然用的是雪花算法
      id-type: auto

oss:
  accessKey: lVtkh5ymwo6865qM0gs1ZGVraHXkLnEMr-TERFul
  secretKey: bgbC2ApuhePJTSbl05tZBwstD59tw4cw2wZhNUal
  bucket: blog-lsc
  cdn: http://rmwprhn2h.hn-bkt.clouddn.com/